lsi: false
safe: true

source: .

title: 100 Automations
email: 100Automations@hackforla.org
description: The 100 Automations project showcases Hack for LA automations and microservices that reduce repetitive work in open source development.

baseurl: "/Website"
url: https://100automations.github.io
repository: 100Automations/Website

sass:
  sass_dir: _sass
  style: compressed

collections:
  memes:
  automations:
  guides:
    output: true
  pages:
    output: true
  bios:
    output: true

defaults:
  - 
    scope:
      path: ""
      type: "guides"
    values:
      layout: "guides"
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "guides"
  - 
    scope:
      path: ""
      type: "bios"
    values:
      layout: "bios"
  - 
    scope:
      path: ""
    values:
      layout: "default"
