version: "3"
services:
  website:
    image: jekyll/jekyll:pages
    container_name: website
    command: jekyll serve --force_polling --livereload --config _config.yml,_config.docker.yml --incremental
    environment:
      - JEKYLL_ENV=docker
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll